version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWOR=postgres
      - POSTGRES_DB=CatalogDb
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgressql/data/    